# Generated by Django 5.1 on 2024-09-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_products', '0004_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('APPROVED', 'Approved'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=9),
        ),
    ]
