# Generated by Django 5.1 on 2024-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Animal Categories',
                'ordering': ('pk',),
            },
        ),
    ]
