# Generated by Django 5.1 on 2024-08-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalblog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=130)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalblog_app.animalcategory')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animalblog_app.author')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
